management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

server:
  port: 8082
eureka:
  client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka
   register-with-eureka: true


spring:
  application:
    name: spring-cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: covidmodule
          uri: lb://COVID19API
          predicates:
            - Path=/covid/**
        - id: consumermodule
          uri: lb://GEODATAAPI
          predicates:
            - Path=/geodata/**